### ISSUE TITLE
Error: java.lang  Invalid reference index -1

### ISSUE THREAD

**Issue by bopohdr** [ssadedin/ximmer#15]
Thank You for solving previous issue. 
After update of Ximmer I am getting another error: 
java.lang.IllegalArgumentException: Invalid reference index -1 . 

Running with :
```
docker run 
-e XIMMER_REF=/reference/hg38.fa 
-v /Users/dmitrijsrots/Downloads/NGS_dati/reference:/reference 
-v /Users/dmitrijsrots/Downloads/NGS_dati/data:/data 
ximmer ximmer 
-c /data/config.groovy
 -o data/output.docker
```

```
Config.groovy file: 
Title="CNV_NGS_meginajums"
bam_files="/data/BAM/*.bam"
target_regions="/data/Trusight_one.bed"
simulation_type="downsample"
concurrency=12
enable_parallel_analyses=true
runs=1
regions=2..10
deletionPerSample=2
callers {
    xhmm {}
    exomedepth {}
}
```
.fa files was indexed using Samtools. Do not know if I could specify somehow .fa.fai file somehow ? 
BAM was aligned to Hg38 with alt contigs using Sentieon (BWA aligner). Software fails to find indexed .fa with alt contigs and downloaded from UCSC. 

Fails with:
```

Using reference sequence: /reference/hg38.fa
2018-11-04T12:27:58.663919247Z 
  | |/ /(_)___ ___  ____ ___  ___  _____
  |   // / __ `__ \/ __ `__ \/ _ \/ ___/
 /   |/ / / / / / / / / / / /  __/ /    
/_/|_/_/_/ /_/ /_/_/ /_/ /_/\___/_/     
2018-11-04T12:27:58.663952910Z 
Install directory detected as: /usr/local/ximmer
2018-11-04T12:27:58.668501431Z 
Reference has been set to /reference/hg38.fa
**************************************************
2018-11-04T12:28:00.190358687Z 
#     #  ###  #     #  #     #  #######  ######   
 #   #    #   ##   ##  ##   ##  #        #     #  
  # #     #   # # # #  # # # #  #        #     #  
   #      #   #  #  #  #  #  #  #####    ######   
  # #     #   #     #  #     #  #        #   #    
 #   #    #   #     #  #     #  #        #    #   
#     #  ###  #     #  #     #  #######  #     #  
2018-11-04T12:28:00.190419476Z 
**************************************************
WARNING: BAM index file /data/BAM/ZL1211.R1_001_rmdup.bai is older than BAM /data/BAM/ZL1211.R1_001_rmdup.bam
WARNING: BAM index file /data/BAM/ZL1211.R1_001_rmdup.bai is older than BAM /data/BAM/ZL1211.R1_001_rmdup.bam
WARNING: BAM index file /data/BAM/ZL1211.R1_001_rmdup.bai is older than BAM /data/BAM/ZL1211.R1_001_rmdup.bam
WARNING: BAM index file /data/BAM/ZL1211.R1_001_rmdup.bai is older than BAM /data/BAM/ZL1211.R1_001_rmdup.bam
WARNING: BAM index file /data/BAM/ZL1211.R1_001_rmdup.bai is older than BAM /data/BAM/ZL1211.R1_001_rmdup.bam
WARNING: BAM index file /data/BAM/ZL1211.R1_001_rmdup.bai is older than BAM /data/BAM/ZL1211.R1_001_rmdup.bam
WARNING: BAM index file /data/BAM/ZL1211.R1_001_rmdup.bai is older than BAM /data/BAM/ZL1211.R1_001_rmdup.bam
WARNING: BAM index file /data/BAM/ZL1211.R1_001_rmdup.bai is older than BAM /data/BAM/ZL1211.R1_001_rmdup.bam
WARNING: BAM index file /data/BAM/ZL1211.R1_001_rmdup.bai is older than BAM /data/BAM/ZL1211.R1_001_rmdup.bam
java.lang.IllegalArgumentException: Invalid reference index -1
	at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
	at gngs.SAM.eachPair(SAM.groovy:649)
	at gngs.SAM.eachPair(SAM.groovy)
	at gngs.SAM.toPairRegions(SAM.groovy:983)
	at gngs.SAM$toPairRegions.call(Unknown Source)
	at CNVSimulator.findCleanRegion(CNVSimulator.groovy:557)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at CNVSimulator$_selectRegion_closure19.doCall(CNVSimulator.groovy:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at ximmer.Exclusions.tryReserve(Exclusions.groovy:57)
	at ximmer.Exclusions$tryReserve.call(Unknown Source)
	at CNVSimulator.selectRegion(CNVSimulator.groovy:632)
	at CNVSimulator$selectRegion.call(Unknown Source)
	at Ximmer$_selectSampleCNVRegion_closure35.doCall(Ximmer.groovy:989)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at gngs.Utils.withRetries(Utils.groovy:313)
	at gngs.Utils$withRetries.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at Ximmer.selectSampleCNVRegion(Ximmer.groovy:977)
	at Ximmer$selectSampleCNVRegion$5.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at Ximmer.selectSampleCNVRegions(Ximmer.groovy:951)
	at Ximmer$selectSampleCNVRegions$4.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at Ximmer.simulateSampleCNVs(Ximmer.groovy:899)
	at Ximmer$simulateSampleCNVs$3.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at Ximmer.simulateSampleCNVs(Ximmer.groovy:823)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1086)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at groovyx.gpars.pa.CallClosure.call(CallClosure.java:47)
	at groovyx.gpars.pa.ClosureMapper.op(ClosureMapper.java:36)
	at groovyx.gpars.extra166y.AbstractParallelAnyArray$OOMPap.leafTransfer(AbstractParallelAnyArray.java:2255)
	at groovyx.gpars.extra166y.PAS$FJOMap.atLeaf(PAS.java:258)
	at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:108)
	at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
	at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
	at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
	at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
Caught: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Invalid reference index -1
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Invalid reference index -1
	at jsr166y.ForkJoinTask.getThrowableException(ForkJoinTask.java:504)
	at jsr166y.ForkJoinTask.reportResult(ForkJoinTask.java:567)
	at jsr166y.ForkJoinTask.join(ForkJoinTask.java:611)
	at jsr166y.ForkJoinPool.invoke(ForkJoinPool.java:1492)
	at groovyx.gpars.extra166y.AbstractParallelAnyArray.allObjects(AbstractParallelAnyArray.java:306)
	at groovyx.gpars.extra166y.ParallelArrayWithMapping.all(ParallelArrayWithMapping.java:141)
	at groovyx.gpars.GParsPoolUtil.collectParallel(GParsPoolUtil.java:495)
	at Ximmer$_simulateRun_closure28.doCall(Ximmer.groovy:765)
	at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy:174)
	at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy)
	at groovyx.gpars.GParsPool.withExistingPool(GParsPool.groovy:173)
	at groovyx.gpars.GParsPool$withExistingPool$1.callStatic(Unknown Source)
	at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:145)
	at groovyx.gpars.GParsPool$withPool$0.callStatic(Unknown Source)
	at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:121)
	at groovyx.gpars.GParsPool$withPool.call(Unknown Source)
	at Ximmer.simulateRun(Ximmer.groovy:764)
	at Ximmer$simulateRun$1.callCurrent(Unknown Source)
	at Ximmer.processRun(Ximmer.groovy:320)
	at Ximmer$processRun$0.callCurrent(Unknown Source)
	at Ximmer.simulate(Ximmer.groovy:297)
	at Ximmer.run(Ximmer.groovy:196)
	at Ximmer$run.call(Unknown Source)
	at Ximmer.main(Ximmer.groovy:1279)
Caused by: java.lang.IllegalArgumentException: Invalid reference index -1
	at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
	at gngs.SAM.eachPair(SAM.groovy:649)
	at gngs.SAM.eachPair(SAM.groovy)
	at gngs.SAM.toPairRegions(SAM.groovy:983)
	at gngs.SAM$toPairRegions.call(Unknown Source)
	at CNVSimulator.findCleanRegion(CNVSimulator.groovy:557)
	at CNVSimulator$_selectRegion_closure19.doCall(CNVSimulator.groovy:633)
	at ximmer.Exclusions.tryReserve(Exclusions.groovy:57)
	at ximmer.Exclusions$tryReserve.call(Unknown Source)
	at CNVSimulator.selectRegion(CNVSimulator.groovy:632)
	at CNVSimulator$selectRegion.call(Unknown Source)
	at Ximmer$_selectSampleCNVRegion_closure35.doCall(Ximmer.groovy:989)
	at gngs.Utils.withRetries(Utils.groovy:313)
	at gngs.Utils$withRetries.call(Unknown Source)
	at Ximmer.selectSampleCNVRegion(Ximmer.groovy:977)
	at Ximmer$selectSampleCNVRegion$5.callCurrent(Unknown Source)
	at Ximmer.selectSampleCNVRegions(Ximmer.groovy:951)
	at Ximmer$selectSampleCNVRegions$4.callCurrent(Unknown Source)
	at Ximmer.simulateSampleCNVs(Ximmer.groovy:899)
	at Ximmer$simulateSampleCNVs$3.callCurrent(Unknown Source)
	at Ximmer.simulateSampleCNVs(Ximmer.groovy:823)
	at groovyx.gpars.pa.CallClosure.call(CallClosure.java:47)
	at groovyx.gpars.pa.ClosureMapper.op(ClosureMapper.java:36)
	at groovyx.gpars.extra166y.AbstractParallelAnyArray$OOMPap.leafTransfer(AbstractParallelAnyArray.java:2255)
	at groovyx.gpars.extra166y.PAS$FJOMap.atLeaf(PAS.java:258)
	at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:108)
	at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
	at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
	at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
	at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
```

**Comment by bopohdr** [comment]
Solved by using hg19

**Comment by ssadedin** [comment]
Out of curiosity, which genome was it that was failing? I have actively used on GRCh37 and hg19 but I can imagine GRCh38 might throw up an issue even though there should be no fundamental problem.

**Comment by bopohdr** [comment]
Grch38 without alt contings: GRCh38.no_alt_analysis_set.fa.gz

**Comment by ssadedin** [comment]
thanks! I will check out if I can reproduce with a similar setup. Definitely want Ximmer to work with build 38.

**Comment by SafinaAr** [comment]
I was using for HG19 and GRCh37
