### ISSUE TITLE
ERROR: analysis pipeline did not produce expected analysed target region BED (running through docker)

### ISSUE THREAD

**Issue by xexpanderx** [ssadedin/ximmer#23]
This is the error:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script15555797947551577614884.groovy: 87: unable to resolve class gngs.BED 
 @ line 87, column 18.
   target_regions = new gngs.BED(target_bed).load()
                    ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:254)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:211)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:221)
	at groovy.lang.GroovyClassLoader$parseClass.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at bpipe.Runner.main(Runner.groovy:436)
	... 6 more

Caught: java.lang.RuntimeException: ERROR: analysis pipeline did not produce expected analysed target region BED: /data/Ximmer/Output/run1/regions.analysable.bed
java.lang.RuntimeException: ERROR: analysis pipeline did not produce expected analysed target region BED: /data/Ximmer/Output/run1/regions.analysable.bed
	at Ximmer.generateReport(Ximmer.groovy:1045)
	at Ximmer$generateReport$5.callCurrent(Unknown Source)
	at Ximmer.run(Ximmer.groovy:202)
	at Ximmer$run.call(Unknown Source)
	at Ximmer.main(Ximmer.groovy:1279)
```

I run it like this:

`docker run -e XIMMER_REF=/genome_fasta/hg19.with.mt.fasta -v /data/ref_genomes/hg19/genome_fasta/:/genome_fasta -v /projects/wp3/nobackup/Workspace/:/data ximmer ximmer -c /data/Ximmer/Config/config.txt -v -o /data/Ximmer/Output -nosim`

My config.txt file:

```
bam_files="/data/CNV/BAM_filter_artifakter2/*.bam"
target_regions="/data/Ximmer/Target_region/regions.bed"
concurrency=20
callers {
    xhmm {}
    exomedepth {}
    conifer {
    	conifer_svd_num=5
    	conifer_call_threshold=1.3}
    cnmops {}
    codex {}
}
```

**Comment by jezkoski** [comment]
Is there a solution for this? I got the same error when trying to run the analysis.

**Comment by kokyriakidis** [comment]
Me too! The same problem! @ssadedin any thoughts?

**Comment by zhq90** [comment]
Me too! Having the same problem! Do you have any solutions on this?@ssadedin
