### ISSUE TITLE
Docker - Tables are not installed

### ISSUE THREAD

**Issue by bopohdr** [ssadedin/ximmer#28]
Having troubles running Conifer with Ximmer:
```
ERROR: stage conifer_rpkm failed: Command in stage conifer_rpkm failed with exit status = 1 : 
LD_LIBRARY_PATH=$HDF5_DIR/lib python /usr/local/ximmer/eval/pipeline/tools/conifer/0.2.2/conifer.py rpkm  --probes Trusight_hg19_XYonly.analysable.bed --output analysis/cfr/rpkms/12-D-120ARVD_S1_L001_001.rpkm --input /data/BAM/XX/12-D-120ARVD_S1_L001_001_rmdup.bam 
Traceback (most recent call last):
  File "/usr/local/ximmer/eval/pipeline/tools/conifer/0.2.2/conifer.py", line 31, in <module>
    import conifer_functions as cf
  File "/usr/local/ximmer/eval/pipeline/tools/conifer/0.2.2/conifer_functions.py", line 28, in <module>
    from tables import *
ImportError: No module named tables
ERROR: stage conifer_rpkm failed: Command in stage conifer_rpkm failed with exit status = 1 : 
LD_LIBRARY_PATH=$HDF5_DIR/lib python /usr/local/ximmer/eval/pipeline/tools/conifer/0.2.2/conifer.py rpkm  --probes Trusight_hg19_XYonly.analysable.bed --output analysis/cfr/rpkms/19-ZL1499_ARVD_S11_L001_001.rpkm --input /data/BAM/XX/19-ZL1499_ARVD_S11_L001_001_rmdup.bam 
ERROR: stage conifer_rpkm failed: Command in stage conifer_rpkm failed with exit status = 1 : 
LD_LIBRARY_PATH=$HDF5_DIR/lib python /usr/local/ximmer/eval/pipeline/tools/conifer/0.2.2/conifer.py rpkm  --probes Trusight_hg19_XYonly.analysable.bed --output analysis/cfr/rpkms/34-ZL873_ARVD_S28_L001_001.rpkm --input /data/BAM/XX/34-ZL873_ARVD_S28_L001_001_rmdup.bam 
ERROR: stage conifer_rpkm failed: Command in stage conifer_rpkm failed with exit status = 1 : 
LD_LIBRARY_PATH=$HDF5_DIR/lib python /usr/local/ximmer/eval/pipeline/tools/conifer/0.2.2/conifer.py rpkm  --probes Trusight_hg19_XYonly.analysable.bed --output analysis/cfr/rpkms/16-ZL556_ARVD_S8_L001_001.rpkm --input /data/BAM/XX/16-ZL556_ARVD_S8_L001_001_rmdup.bam 
========================================= Pipeline Failed ==========================================
One or more parallel stages aborted. The following messages were reported:
----------------------- conifer_rpkm  ( 19-ZL1499_ARVD_S11_L001_001_rmdup )  -----------------------
Command in stage conifer_rpkm failed with exit status = 1 : 
LD_LIBRARY_PATH=$HDF5_DIR/lib python /usr/local/ximmer/eval/pipeline/tools/conifer/0.2.2/conifer.py rpkm  --probes Trusight_hg19_XYonly.analysable.bed --output analysis/cfr/rpkms/19-ZL1499_ARVD_S11_L001_001.rpkm --input /data/BAM/XX/19-ZL1499_ARVD_S11_L001_001_rmdup.bam
```

I checked, the tables are not installed in the docker image for ximmer
```
docker run -it ssadedin/ximmer                             
root@571cab9639a9:/# pip list
argparse (1.2.1)
chardet (2.0.1)
colorama (0.2.5)
html5lib (0.999)
numpy (1.15.4)
pandas (0.23.4)
pip (1.5.4)
pycurl (7.19.3)
pysam (0.15.1)
python-apt (0.9.3.5ubuntu3)
python-dateutil (2.7.5)
pytz (2018.7)
requests (2.2.1)
setuptools (3.3)
six (1.5.2)
urllib3 (1.7.1)
wheel (0.24.0)
wsgiref (0.1.2)
```
I think it could be solved by providing changing dockerfile, but unfortunately, I was unable to do it myself.

**Comment by hkrzystek** [comment]
Hi bopohdr, I am also using the Docker container but through Singularity. Have you gotten a similar error to what I posted about here: 
https://github.com/ssadedin/ximmer/issues/29#issue-491290005

I am not sure if it is an issue with singularity or the Docker container itself. 

Thanks!

**Comment by bopohdr** [comment]
To be able to run Conifer via ximmer in docker, I had to:

1) change dockerfile and add necessary environment (including tables and pandas):
`RUN apt-get install -y openjdk-8-jre && apt-get install -y libfreetype6-dev pkg-config python-dev python-pip python2.7	cython 	libhdf5-serial-dev python-pandas python-tables python-matplotlib
` 
2) modify Conifer (conifer.py) code as described here : https://sourceforge.net/p/conifer/discussion/general/thread/d2fbc181/ 
 ( change in conifer.py file
`not f._hasIndex()`
to
`f.check_index()`
and re-upload necessary files to sourceforge )
3) Change the download source for Conifer in bpipe.config file:
         ` curl -o 'conifer-0.2.2.tar.gz' 'https://master.dl.sourceforge.net/project/conifer-for-ximmer/conifer-0.2.2.tar.gz'`
