### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SamKap-2** [ssadedin/ximmer#9]
Could you throw some light on this error
bpipe.PipelineError: Error evaluating script '~/ximmer/eval/pipeline/config.groovy': No such property: HGFA for class: ~/ximmer/eval/pipeline/config.groovy
        at bpipe.Pipeline$_loadExternalStagesFromPathList_closure14.doCall(Pipeline.groovy:1027)
        at bpipe.Pipeline.loadExternalStagesFromPathList(Pipeline.groovy:1000)
        at bpipe.Pipeline.loadExternalStagesFromPaths(Pipeline.groovy:982)
        at bpipe.Pipeline.loadExternalStagesFromPaths(Pipeline.groovy)
        at bpipe.Pipeline.load(Pipeline.groovy:1107)
        at exome_cnv_pipeline.groovy.run(exome_cnv_pipeline.groovy:30)
        at exome_cnv_pipeline.groovy$run.call(Unknown Source)
        at bpipe.Runner.main(Runner.groovy:439)

**Comment by ssadedin** [comment]
Apologies, it looks like the installer is not setting this up properly.

I'll get a fix in for it, but in the meantime, could you try editing the file

`~/ximmer/eval/pipeline/config.groovy`

And in there, put a line like so:

```
HGFA="/path/to/genome/reference.fa"
```

Where you need to replace that reference with the same reference that your BAM files are aligned to.

**Comment by SamKap-2** [comment]
Thanks Simon
